module cpu(
    input clk,
    input reset
);

    // ========================================================================
    // FETCH STAGE (IF)
    // ========================================================================
    
    wire [31:0] pc_out;              // Current PC value
    wire [31:0] next_pc;             // Next PC (either PC+4 or branch/jump target)
    wire [31:0] instruction;         // Fetched instruction from memory
    
    // IF/ID Pipeline Register Outputs
    wire [31:0] id_pc;               // PC value in decode stage
    wire [31:0] id_instruction;      // Instruction in decode stage

    // ========================================================================
    // DECODE STAGE (ID)
    // ========================================================================
    
    // Decoded instruction fields
    wire [6:0] id_opcode;
    wire [4:0] id_rd, id_rs1, id_rs2;
    wire [2:0] id_funct3;
    wire [6:0] id_funct7;
    
    // Immediate values (one per instruction type)
    wire [31:0] id_imm_i, id_imm_s, id_imm_b, id_imm_u, id_imm_j;
    reg  [31:0] id_imm_val;          // Selected immediate based on instruction type

    // Control signals generated by control unit
    wire [3:0] id_alu_op;
    wire id_alu_src, id_reg_write, id_mem_write, id_mem_read, id_mem_to_reg;
    wire id_branch, id_jump, id_jump_jal, id_jump_jalr, id_pc_to_alu;

    // Register file outputs
    wire [31:0] id_read_data1, id_read_data2;

    // ========================================================================
    // EXECUTE STAGE (EX)
    // ========================================================================
    
    // ID/EX Pipeline Register Outputs
    wire [31:0] ex_pc, ex_read_data1, ex_read_data2, ex_imm_val;
    wire [4:0] ex_rs1, ex_rs2, ex_rd;
    wire [2:0] ex_funct3;
    wire [3:0] ex_alu_op;
    wire ex_alu_src, ex_reg_write, ex_mem_write, ex_mem_read, ex_mem_to_reg;
    wire ex_branch, ex_jump, ex_jump_jal, ex_jump_jalr, ex_pc_to_alu;

    // ALU signals
    wire [31:0] ex_alu_input_a, ex_alu_input_b;  // ALU inputs after forwarding
    wire [31:0] ex_alu_result;                    // ALU output
    
    // Branch/jump signals
    wire ex_branch_taken;                          // Branch condition result
    wire [31:0] ex_branch_target;                  // Calculated branch target
    wire [31:0] ex_pc_plus_4;                      // Return address for jumps

    // Forwarding and hazard detection
    wire [1:0] forward_a, forward_b;               // Forwarding control signals
    wire stall;                                    // Pipeline stall signal
    reg [31:0] forwarded_rdata1, forwarded_rdata2; // Register data after forwarding

    // ========================================================================
    // MEMORY STAGE (MEM)
    // ========================================================================
    
    // EX/MEM Pipeline Register Outputs
    wire [31:0] mem_alu_result, mem_read_data2, mem_pc_plus_4;
    wire [4:0] mem_rd;
    wire mem_reg_write, mem_mem_write, mem_mem_read, mem_mem_to_reg, mem_jump;

    // Data memory output
    wire [31:0] mem_read_data;                     // Data loaded from memory
    wire [31:0] mem_forward_data;                  // Data to forward (memory or ALU result)

    // ========================================================================
    // WRITEBACK STAGE (WB)
    // ========================================================================
    
    // MEM/WB Pipeline Register Outputs
    wire [31:0] wb_alu_result, wb_mem_data, wb_pc_plus_4;
    wire [4:0] wb_rd;
    wire wb_reg_write, wb_mem_to_reg, wb_jump;

    // Final writeback value
    wire [31:0] wb_reg_write_data;                 // Final data written to register file

    // ========================================================================
    // CONTROL HAZARD SIGNALS
    // ========================================================================
    
    wire flush;                                     // Flush pipeline on control hazard
    wire control_hazard;                            // Branch taken or jump occurred
    wire [31:0] target_pc;                          // Branch/jump target address

    // ========================================================================
    // FETCH STAGE MODULES
    // ========================================================================
    
    program_counter pc_inst (
        .clk(clk),
        .reset(reset),
        .pc_enable(!stall),                         // Freeze PC during stalls
        .next_pc(next_pc),
        .pc_out(pc_out)
    );

    instruction_memory imem_inst (
        .address(pc_out),
        .instruction(instruction)
    );

    if_id if_id_instance (
        .clk(clk),
        .reset(reset || flush),                     // Flush on control hazard
        .enable(!stall),                            // Hold during stalls
        .pc(pc_out),
        .instruction(instruction),
        .id_pc(id_pc),
        .id_instruction(id_instruction)
    );

    // ========================================================================
    // DECODE STAGE MODULES
    // ========================================================================

    instruction_decoder decoder_inst (
        .instruction(id_instruction),
        .opcode(id_opcode),
        .rd(id_rd),
        .funct3(id_funct3),
        .rs1(id_rs1),
        .rs2(id_rs2),
        .funct7(id_funct7),
        .imm_i(id_imm_i),
        .imm_s(id_imm_s),
        .imm_b(id_imm_b),
        .imm_u(id_imm_u),
        .imm_j(id_imm_j)
    );

    control_unit control_inst (
        .opcode(id_opcode),
        .funct3(id_funct3),
        .funct7(id_funct7),
        .alu_op(id_alu_op),
        .alu_src(id_alu_src),
        .reg_write(id_reg_write),
        .mem_write(id_mem_write),
        .mem_read(id_mem_read),
        .mem_to_reg(id_mem_to_reg),
        .branch(id_branch),
        .jump(id_jump),
        .jump_jal(id_jump_jal),
        .jump_jalr(id_jump_jalr),
        .pc_to_alu(id_pc_to_alu)
    );

    register_file regf_inst (
        .clk(clk),
        .reset(reset),
        .rs1(id_rs1),
        .rs2(id_rs2),
        .rd(wb_rd),                                 // Write happens in WB stage
        .write_data(wb_reg_write_data),
        .reg_write(wb_reg_write),
        .rdata1(id_read_data1),
        .rdata2(id_read_data2)
    );

    id_ex id_ex_instance (
        .clk(clk),
        .reset(reset),
        .enable(1'b1),
        .pc(id_pc),
        
        // Data signals
        .read_data1(id_read_data1),
        .read_data2(id_read_data2),
        .imm_val(id_imm_val),
        .rs1(id_rs1),
        .rs2(id_rs2),
        .rd(id_rd),
        .funct3(id_funct3),
        .alu_op(id_alu_op),
        .alu_src(id_alu_src),
        
        // Control signals - zeroed on stall or flush to insert bubbles
        .reg_write((stall || flush) ? 1'b0 : id_reg_write),
        .mem_write((stall || flush) ? 1'b0 : id_mem_write),
        .mem_read((stall || flush) ? 1'b0 : id_mem_read),
        .mem_to_reg((stall || flush) ? 1'b0 : id_mem_to_reg),
        .branch((stall || flush) ? 1'b0 : id_branch),
        .jump((stall || flush) ? 1'b0 : id_jump),
        .jump_jal((stall || flush) ? 1'b0 : id_jump_jal),
        .jump_jalr((stall || flush) ? 1'b0 : id_jump_jalr),
        .pc_to_alu((stall || flush) ? 1'b0 : id_pc_to_alu),
        
        // Outputs
        .ex_pc(ex_pc),
        .ex_read_data1(ex_read_data1),
        .ex_read_data2(ex_read_data2),
        .ex_imm_val(ex_imm_val),
        .ex_rs1(ex_rs1),
        .ex_rs2(ex_rs2),
        .ex_rd(ex_rd),
        .ex_funct3(ex_funct3),
        .ex_alu_op(ex_alu_op),
        .ex_alu_src(ex_alu_src),
        .ex_reg_write(ex_reg_write),
        .ex_mem_write(ex_mem_write),
        .ex_mem_read(ex_mem_read),
        .ex_mem_to_reg(ex_mem_to_reg),
        .ex_branch(ex_branch),
        .ex_jump(ex_jump),
        .ex_jump_jal(ex_jump_jal),
        .ex_jump_jalr(ex_jump_jalr),
        .ex_pc_to_alu(ex_pc_to_alu)
    );

    // ========================================================================
    // EXECUTE STAGE MODULES
    // ========================================================================

    alu alu_inst (
        .a(ex_alu_input_a),                         // Operand A (with forwarding)
        .b(ex_alu_input_b),                         // Operand B (with forwarding)
        .alu_op(ex_alu_op),
        .result(ex_alu_result)
    );

    forwarding_unit forwarding_unit_instance (
        .ex_rs1(ex_rs1),
        .ex_rs2(ex_rs2),
        .mem_rd(mem_rd),
        .mem_reg_write(mem_reg_write),
        .wb_rd(wb_rd),
        .wb_reg_write(wb_reg_write),
        .forward_a(forward_a),                      // 00=no forward, 01=WB, 10=MEM
        .forward_b(forward_b)
    );

    hazard_detection_unit hazard_detection_unit_instance (
        .id_rs1(id_rs1),
        .id_rs2(id_rs2),
        .ex_rd(ex_rd),
        .ex_mem_read(ex_mem_read),                  // Stall on load-use hazard
        .stall(stall)
    );

    branch_unit branch_unit_instance (
        .rdata1(forwarded_rdata1),                  // Compare forwarded values
        .rdata2(forwarded_rdata2),
        .funct3(ex_funct3),
        .branch(ex_branch),
        .branch_taken(ex_branch_taken)
    );

    ex_mem ex_mem_instance (
        .clk(clk),
        .reset(reset),
        .enable(1'b1),
        
        // Inputs from EX stage
        .alu_result(ex_alu_result),
        .read_data2(forwarded_rdata2),              // Use forwarded data for stores
        .rd(ex_rd),
        .mem_write(ex_mem_write),
        .mem_read(ex_mem_read),
        .mem_to_reg(ex_mem_to_reg),
        .reg_write(ex_reg_write),
        .pc_plus_4(ex_pc_plus_4),
        .jump(ex_jump),
        
        // Outputs to MEM stage
        .mem_alu_result(mem_alu_result),
        .mem_read_data2(mem_read_data2),
        .mem_rd(mem_rd),
        .mem_mem_write(mem_mem_write),
        .mem_mem_read(mem_mem_read),
        .mem_mem_to_reg(mem_mem_to_reg),
        .mem_reg_write(mem_reg_write),
        .mem_pc_plus_4(mem_pc_plus_4),
        .mem_jump(mem_jump)
    );

    // ========================================================================
    // MEMORY STAGE MODULES
    // ========================================================================

    data_memory data_mem_inst (
        .clk(clk),
        .address(mem_alu_result),                   // Address from ALU
        .write_data(mem_read_data2),                // Data to store
        .mem_write(mem_mem_write),
        .mem_read(mem_mem_read),
        .read_data(mem_read_data)                   // Data loaded from memory
    );

    mem_wb mem_wb_instance (
        .clk(clk),
        .reset(reset),
        .enable(1'b1),
        
        // Inputs from MEM stage
        .alu_result(mem_alu_result),
        .mem_data(mem_read_data),
        .pc_plus_4(mem_pc_plus_4),
        .rd(mem_rd),
        .mem_to_reg(mem_mem_to_reg),
        .reg_write(mem_reg_write),
        .jump(mem_jump),
        
        // Outputs to WB stage
        .wb_alu_result(wb_alu_result),
        .wb_mem_data(wb_mem_data),
        .wb_pc_plus_4(wb_pc_plus_4),
        .wb_rd(wb_rd),
        .wb_mem_to_reg(wb_mem_to_reg),
        .wb_reg_write(wb_reg_write),
        .wb_jump(wb_jump)
    );

    // ========================================================================
    // COMBINATIONAL LOGIC - MUXES AND CONTROL
    // ========================================================================

    // Immediate Selector: Pick the right immediate format based on opcode
    // Different instruction types encode immediates in different bit positions
    always @(*) begin
        case (id_opcode)
            7'b0010011: id_imm_val = id_imm_i;      // I-type arithmetic (ADDI, ORI, etc.)
            7'b0000011: id_imm_val = id_imm_i;      // I-type load (LW)
            7'b0100011: id_imm_val = id_imm_s;      // S-type store (SW)
            7'b0110111: id_imm_val = id_imm_u;      // U-type (LUI, AUIPC)
            7'b1100011: id_imm_val = id_imm_b;      // B-type branches
            7'b1101111: id_imm_val = id_imm_j;      // J-type (JAL)
            7'b1100111: id_imm_val = id_imm_i;      // JALR uses I-type format
            default:    id_imm_val = 32'b0;         // R-type has no immediate
        endcase
    end

    // Forwarding Mux A: Select forwarded value for ALU input A
    // Priority: MEM stage (most recent) > WB stage > pipeline register
    always @(*) begin
        case (forward_a)
            2'b10:   forwarded_rdata1 = mem_forward_data;  // Forward from MEM
            2'b01:   forwarded_rdata1 = wb_reg_write_data; // Forward from WB
            default: forwarded_rdata1 = ex_read_data1;     // Use pipeline value
        endcase
    end

    // Forwarding Mux B: Select forwarded value for ALU input B
    always @(*) begin
        case (forward_b)
            2'b10:   forwarded_rdata2 = mem_forward_data;  // Forward from MEM
            2'b01:   forwarded_rdata2 = wb_reg_write_data; // Forward from WB
            default: forwarded_rdata2 = ex_read_data2;     // Use pipeline value
        endcase
    end

    // MEM Forwarding Data Mux: Choose between memory data or ALU result
    // Memory loads need to forward the loaded data, not the address
    assign mem_forward_data = (mem_mem_to_reg) ? mem_read_data : mem_alu_result;

    // ALU Input A Mux: Choose between PC or register for ALU input
    // PC is used for jump target calculations
    assign ex_alu_input_a = (ex_pc_to_alu) ? ex_pc : forwarded_rdata1;
    
    // ALU Input B Mux: Choose between immediate or register for ALU input
    // Most instructions use immediate (ADDI, LW, SW, branches, etc.)
    assign ex_alu_input_b = (ex_alu_src) ? ex_imm_val : forwarded_rdata2;

    // Branch target calculation: PC + branch offset
    assign ex_branch_target = ex_pc + ex_imm_val;

    // Return address for JAL/JALR: address of instruction after the jump
    assign ex_pc_plus_4 = ex_pc + 4;

    // Control Hazard Detection: Flush pipeline when branch taken or jump occurs
    assign control_hazard = (ex_branch && ex_branch_taken) || (ex_jump && (ex_jump_jal || ex_jump_jalr));
    
    // Target PC Calculation: JALR uses register+offset, others use PC+offset
    assign target_pc = (ex_jump_jalr) ? (ex_read_data1 + ex_imm_val) : (ex_pc + ex_imm_val);

    // Flush signal for pipeline: insert NOPS after control hazard
    assign flush = control_hazard;

    // PC Mux: Choose between branch/jump target or sequential PC+4
    assign next_pc = flush ? target_pc : pc_out + 4;

    // Writeback Data Mux: Choose between PC+4 (jumps), memory data (loads), 
    // or ALU result (arithmetic/logic)
    assign wb_reg_write_data = (wb_jump) ? wb_pc_plus_4 : ((wb_mem_to_reg) ? wb_mem_data : wb_alu_result);


    // Debug output assignments
    assign debug_pc = pc_out;
    assign debug_instruction = id_instruction;
    assign debug_alu_result = mem_alu_result;
    assign debug_rd = mem_rd;

endmodule